### ISSUE TITLE
Ani Information error

### ISSUE THREAD

**Issue by kkcc1213** [IrfanKhan66/hianime-mapper#2]
can you try this id "103294"
anime url: https://hianime.to/banished-from-the-heroes-party-17372
https://hianime-mapper.vercel.app/anime/info/103294
return "Internal server issue !"

**Comment by IrfanKhan66** [comment]
> can you try this id "103294" anime url: https://hianime.to/banished-from-the-heroes-party-17372 https://hianime-mapper.vercel.app/anime/info/103294 return "Internal server issue !"

The Id you provided it is the manga Id and not the Anime Id use the Anime Id only
