### ISSUE TITLE
[Ask] How to get anime list id?

### ISSUE THREAD

**Issue by kkcc1213** [IrfanKhan66/hianime-mapper#3]
i new for this sry sir
How to get anime list id?
like in https://hianime.to/banished-from-the-heroes-party-17372
i find in develop tool
i see anilist_id = 103294
but you say it manga Id and not the Anime Id
<script id="syncData" type="application/json">
    {
        "page":"anime",
        "name":"Banished From the Heroes&#39; Party",
        "anime_id":"17372",
        "mal_id":"44037",
        "anilist_id":"103294",
        "series_url":"https://hianime.to/banished-from-the-heroes-party-17372",
        "selector_position":"#mal-sync"
    }
</script>
you do have another way to find can you tell me how sir?

**Comment by IrfanKhan66** [comment]
> i new for this sry sir How to get anime list id? like in https://hianime.to/banished-from-the-heroes-party-17372 i find in develop tool i see anilist_id = 103294 but you say it manga Id and not the Anime Id
> 
> <script id="syncData" type="application/json"> { "page":"anime", "name":"Banished From the Heroes' Party", "anime_id":"17372", "mal_id":"44037", "anilist_id":"103294", "series_url":"https://hianime.to/banished-from-the-heroes-party-17372", "selector_position":"#mal-sync" } </script>
> you do have another way to find can you tell me how sir?

use this API: [Anilist Api](https://anilist.gitbook.io/anilist-apiv2-docs/overview/graphql/getting-started)
