### ISSUE TITLE
return null

### ISSUE THREAD

**Issue by kkcc1213** [IrfanKhan66/hianime-mapper#4]
hi i try to get link from https://hianime.to/dead-mount-death-play-part-2-18583
https://hianime-mapper.vercel.app/anime/info/162803
"dead-mount-death-play-part-2-18583?ep=107938" 
EP 1 EPID=107938
https://hianime-mapper.vercel.app/anime/servers/107938
for DUB
"serverId": "1060527",
"serverName": "HD-1"
After Server ID and Episode ID 
https://hianime-mapper.vercel.app/anime/sources?serverId=1060527&episodeId=107938
it return null 
what wrong with it? sir

**Comment by IrfanKhan66** [comment]
There might have been new changes or update of Hianime backend, therefore the API broke. I am not looking forward to currently fix the API instead after sometime but anyone is allowed to contribute in fixing this issue.
