### ISSUE TITLE
Kindly update demo url.

### ISSUE THREAD

**Issue by BlazeCoderLab** [IrfanKhan66/hianime-mapper#5]
Hi there dear 👋🏻,
Hope you are doing great. Can you please update the demo url as it seems it went down. Also if you don't mind can we talk on discord or telegram. I'm working on an anime website and i see you're pretty much expert in it so i want to take your help where i got stuck.
Please if possible then help me out.
Discord: @maverick.harry
Telegram: [https://t.me/animax_fan](https://t.me/animax_fan)

**Comment by IrfanKhan66** [comment]
> Hi there dear 👋🏻, Hope you are doing great. Can you please update the demo url as it seems it went down. Also if you don't mind can we talk on discord or telegram. I'm working on an anime website and i see you're pretty much expert in it so i want to take your help where i got stuck. Please if possible then help me out. Discord: @maverick.harry Telegram: https://t.me/animax_fan

I have stopped working on this project long ago, and my render.com hosting limit is over that's why the demo url isn't working. I'll reach you on discord or tg when i get free
