### ISSUE TITLE
Only need hep for the secret

### ISSUE THREAD

**Issue by boxkim14** [IrfanKhan66/hianime-mapper#6]
Hi,

Your mapper is very great but I am not expert on JS then I cannot understand the extractVariables  and getSecret  method in decrypt.ts.
I would like to convert them into python. If you don't mind, can you please help me?

Thanks in advance for your help.

**Comment by IrfanKhan66** [comment]
The scraper is outdated I haven't tested it in months so it might not work !, and as for the getSecret method it isn't a constant it is called in megacloud.ts file where it depends on the vars variables provided to it in the second argument which is also depends on the response from megacloud
